"""add_pause_fields_to_time_entries

Revision ID: 60eb965eabc3
Revises: d328763a4d1c
Create Date: 2026-03-21 11:35:38.396609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60eb965eabc3'
down_revision: Union[str, Sequence[str], None] = 'd328763a4d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('time_entries', sa.Column('paused_seconds', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_entries', 'paused_seconds')
    op.drop_column('time_entries', 'paused_at')
    # ### end Alembic commands ###
